version: 1
updates:
  # 1) Actualizaciones para dependencias de npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"        # daily | weekly | monthly
    open-pull-requests-limit: 5 # max PRs abiertas
    versioning-strategy: increase # always bump to latest allowed version
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
      include: "scope"

  # 2) Actualizaciones para GitHub Actions (muy recomendado)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ci"
      - "dependencies"
    commit-message:
      prefix: "ci"
      include: "scope"